### ISSUE TITLE
Separating tags with commas

### ISSUE THREAD

**Issue by jaimeiniesta** [maxmarcon/live_select#15]
Hi, as a followup to https://github.com/maxmarcon/live_select/issues/11, it would be great to enter several tags by the use of the comma (`,`)  character, as in this example:

https://codepen.io/atomgiant/pen/QWjWgKz

That is if you type `tag1,tag2,tag3` you end up with 3 independent tags: `tag1`, `tag2` and `tag3`.

How could we achieve this behavior?

**Comment by maxmarcon** [comment]
I don't see an advantage in using this when users type in the tags one by one. What's the advantage of ending each tag with a comma as opposed to using the enter key?

I think your use case was more like when the user wants to copy and paste text from somewhere else - like a comma separated list of tags from a CSV file or something.

This should probably be configurable: someone might want to use the comma as separator, someone the dot and so on.
Even this might not be enough: maybe someone will want to apply some transformation to the tags, like making them uppercase, or shortening them etc.

How about offering a flexible interface that accommodates all this? The `user_defined_options` parameter could also accept a function or MFA that is called with the text entered by the user and must return the list of tags to add.

So in your case:

```elixir
<%= live_select, mode: :tags, user_defined_options: &split_tags/1 %>

def split_tags(text) do
  String.split(text, ",")
end
```

What do you think?

**Comment by jaimeiniesta** [comment]
Yes, this should be optional and configurable, so your solution sounds fine if it provides the experience in the linked example above.

When working with tags I think that in most cases they're expected to be comma-separated. In my case I don't want to allow commas inside a tag, so that should be used as a separator but yes, that separator character or separator function should be configurable.

**Comment by maxmarcon** [comment]
> Yes, this should be optional and configurable, so your solution sounds fine if it provides the experience in the linked example above.

it would not because in your example the tags are added when the user enters a comma. So the comma key replaces the enter key:

* I type "A" then comma (tag A is added)
* I type "B" then comma (tag B is added)

What I'm proposing is that the user types "A,B,C" (or pastes is from somewhere), then hits Enter, and tags A, B and C are added.

I see no reason for using the comma key as a replacement for the Enter key. Enter is the universal key for entering input, using a comma to communicate "I'm done with entering input" feels kind of unnatural and surprising. And it's also unnecessary because if you want to type the tags one by one, I see no point in using another "enter" key.

Unless I'm missing something of course :)

**Comment by jaimeiniesta** [comment]
Good, I see your point and I think you're right. It feels a bit weird that hitting a comma triggers a label creation, it's more natural that only the "enter" key does that.

So, the user would type "A,B", press Enter, then `A` and `B` tags are added. I think that can work fine.

**Comment by maxmarcon** [comment]
Ok, we have a plan then 👍 

If you want to take a stab at a PR, feel free to. Otherwise I'll try to add this as soon as I find some time.

**Comment by jaimeiniesta** [comment]
Hey, @maxmarcon I finally set up my own tag editor and I'm no longer using live_select so please don't wait me for that PR.

Thanks again!

**Comment by maxmarcon** [comment]
Thanks for letting me know
