### ISSUE TITLE
[Question] Hide dropdown

### ISSUE THREAD

**Issue by Manukam** [maxmarcon/live_select#19]
Hi,

I just want to understand how `@hide_dropdown` is going to work when there are multiple `live_select` on a single page? For example, when `multi_select` is defined inside an `inputs_for`

I see in the code, you use the `@hide_dropdown` variable for this, but when there are more than one `live_select`, how does this work?

**Comment by maxmarcon** [comment]
Like any other assign, `@hide_dropdown` is scoped within the instance of the component. Different components work on different assigns.

Are you experiencing issues when using multiple LiveSelect componentx in the same view or form?

**Comment by Manukam** [comment]
Follow up question to that,

```
<%= if Enum.empty?(@selection) do %>
      <input
        type="hidden"
        name="live_select_empty_selection"
        id={"live_select_empty_selection_#{@myself}"}
        disabled={@disabled}
      />
    <% end %>
    <%= for {value, idx} <- values(@selection) |> Enum.with_index() do %>
      <input
        type="hidden"
        name={input_name(@form, @field) <> "[]"}
        id={input_id(@form, @field) <> "_#{idx}"}
        disabled={@disabled}
        value={value}
      />
    <% end %>
  <% end %>
```

Why is there two hidden inputs here? Wouldn't one work?

**Comment by maxmarcon** [comment]
The first hidden input is rendered when the selection is empty. This is so that we can trigger a change event when the user remove the last selected element in `tags` (multiselection) mode. Go to the showcase app, choose tags mode, select a city, then remove it. You'll see this event:

![image](https://user-images.githubusercontent.com/11156096/222431716-1eb8345f-cd3a-4022-92df-9449a430c709.png)

That event is triggered by the `live_select_empty_selection` hidden input (see the `_target` param). Without that hidden input, we'd have no element in the form to signal the parent that the selection was emptied. HTML forms can't send an empty array.

I added this because I thought it would be good for the parent to receive a change event whenever the selection changes, including when the selection becomes empty.
