### ISSUE TITLE
Crashes LiveView in function maybeHideFeedback

### ISSUE THREAD

**Issue by gtaranti** [maxmarcon/live_select#28]
Using the latest lv v 0.18.18 there is no problem.
But when switching to  LiveView's 'main' gh branch there is a crash on liveview's `dom.js`
For some reason it thinks liveselect input doesn't have a 'name' attribute and fails.

![CleanShot 2023-05-28 at 10 38 29](https://github.com/maxmarcon/live_select/assets/951250/648da1b6-b4b0-40a5-9038-ddb4948bc222)

**Comment by maxmarcon** [comment]
Thanks for the report.

The live_select container does have a name attributes. However, its name attribute is accessed [here](https://github.com/phoenixframework/phoenix_live_view/blob/76cadff532495fdfdef78a11324743399f403218/assets/js/phoenix_live_view/dom.js#L276) using the `.name` property of its HTML object, which is an API only available (I believe) for HTML input elements. And since the live_select container is a div, `.name` returns undefined in this case.

The big question to me is why liveview considers the live_select container an input it should track at all - it's not an HTML input. This happens [here](https://github.com/phoenixframework/phoenix_live_view/blame/76cadff532495fdfdef78a11324743399f403218/assets/js/phoenix_live_view/dom_patch.js#L250), where the container div gets added to the `trackedInputs` array, but it's not clear to me why this happens. 

I will investigate further when I find some time. In the meantime, any help or suggestion is welcome.

**Comment by maxmarcon** [comment]
I opened an [issue on the LV repo](https://github.com/phoenixframework/phoenix_live_view/issues/2648). 

Since they already released LV `0.19.0`, which contains this bug, I will go ahead and remove the name attribute from all non-input elements in live_select and release a new version.

**Comment by maxmarcon** [comment]
Fixed with 43aa84bb0f7b60de559057cd6f71eaae1f60f3ea

New version released: [1.0.4](https://hexdocs.pm/live_select/1.0.4)
