### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by saleyn** [maxmarcon/live_select#4]
In the demo, a change of the dark/light mode doesn't affect the color of the LiveSelect, which always stays white.

**Comment by maxmarcon** [comment]
It depends on which style mode you're using:

- In daisyui mode, the colors will change, because daisyui has built-in support for dark mode via themes
- In tailwind mode the toggle would have no effect

I changed the showcase app so that tailwind will now honor the settings of the toggle.

However, if you use standard tailwind, it's up to you to style the component so that it will apply certain classes only in dark mode. For this purpose you use the `dark` variant: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

Example. Pull the latest changes and run the showcase app locally at port 4000 and open this link:

http://localhost:4000/?active_option_class=&container_class=&container_extra_class=&debounce=100&dropdown_class=&dropdown_extra_class=&field_name=city_search&form_name=my_form&option_class=&option_extra_class=&placeholder=Search+for+a+city&search_delay=10&show_styles=true&style=tailwind&text_input_class=&text_input_extra_class=dark%3Abg-red-200&text_input_selected_class=&update_min_len=

You will see that the background of the text input becomes red when you toggle dark mode. That's because of the setting:

`text_input_extra_class=dark:bg-red-200`

which tells tailwind to use a red background only if dark mode is enabled.
