### ISSUE TITLE
Possible bug in form data handling in 1.3

### ISSUE THREAD

**Issue by JWHnugun** [maxmarcon/live_select#47]
Hello and thanks for this project!

Setting options on initialization like
```heex
<.live_select :if={ @worksite.id != nil }
          field={@form[:project_id]}
          options={ [ {@worksite.project.name,@worksite.project.id} ] }
          phx-target={@myself} />
```
initially fills the select and works as expected but any change to other form fields (also LiveSelect) causes a "validate" and the component resets its displayed value to the .id part of the tuple. If selected it displays the .label part again. There are only LiveSelects in the form 1-3 of them and all reset to the .id.

I am new to Phoenix and LiveView hence the possible in the title. I made a demo with LiveSelect last week (1.2.2) and it worked as expected but after integration (now 1.3) it started to exhibit this strange behavior.

Any advice is welcome, thanks again.

**Comment by maxmarcon** [comment]
Hi! Can you please post the code of your handler for the validate event?

**Comment by maxmarcon** [comment]
I tried to reproduce it and I couldn't.

Can you please show me what `Worksites.change_worksite/2` is doing?

**Comment by maxmarcon** [comment]
My guess is that `@worksite.project.id` is probably an integer but your event handler is casting it into a string in the form, so live_select can't match the value of the selection with the value of the option.

**Comment by JWHnugun** [comment]
I downgraded to 1.2.2 and got it working again without any changes to the project. 
But I think you are right I upgraded to 1.3 again and it failed the same way as before. Then I changed the tuple generation to produce {String.t(),String.t()} tuples and now it fails the other way around. Now it displays the .id initially and validates to the text label if I change something.

```elixir
form #=> %Phoenix.HTML.Form{
  source: #Ecto.Changeset<action: :validate, changes: %{}, errors: [],
   data: #Worksites.Worksite<>, valid?: true>,
  impl: Phoenix.HTML.FormData.Ecto.Changeset,
  id: "worksite",
  name: "worksite",
  data: %Worksites.Worksite{
    __meta__: #Ecto.Schema.Metadata<:loaded, "worksites">,
    id: 6,
    address_id: 4,
    address: %Addresses.Address{
    ...
    },
    project_id: 1,
    project: %Projects.Project{
      __meta__: #Ecto.Schema.Metadata<:loaded, "projects">,
      id: 1,
      customer_id: 1,
      customer: %Customers.Customer{
       ...
      },
      worksites: #Ecto.Association.NotLoaded<association :worksites is not loaded>,
      inserted_at: ~U[2023-11-22 11:35:00Z],
      updated_at: ~U[2023-11-29 12:49:41Z]
    },
    inserted_at: ~U[2023-12-05 13:53:03Z],
    updated_at: ~U[2023-12-05 14:06:10Z]
  },
  hidden: [id: 6],
  params: %{
    "address_id" => "4",
    "address_id_text_input" => "...",
    "project_id" => "1",
    "project_id_text_input" => "..."
  },
  errors: [],
  options: [method: "put"],
  index: nil,
  action: nil
}
```
```elixir
defmodule Worksites.Worksite do
  @doc false
  def changeset(worksite, attrs) do
    worksite
    |> cast(attrs, [:address_id, :project_id, :project_name])
    |> validate_required([:address_id,:project_id])
  end
end
```

**Comment by maxmarcon** [comment]
yes. project_id is a string in your example (params -> project_id).

You need to cast it as an integer in the form, otherwise live_select can't match it to the options (or, you should have it as a string in the options, too).

versions previous to 1.3.0 were ignoring updates to the form, which is a problem because it prevents things like form recovery.

**Comment by JWHnugun** [comment]
That helped thank you!  But it an easy thing to overlook when working with database ids in forms. Which apparently get casted to strings by to_form or somewhere on the way...?

This fixed it but it is kind of ugly IMHO.
```elixir
  @impl true
  def handle_event("validate", %{"worksite" => worksite_params} = param, socket) do
    #Validate/Annotate
    form =
      socket.assigns.worksite
      |> Worksites.change_worksite(worksite_params)
      |> Map.put(:action, :validate)
      |> to_form()

    #Fix ID Types
    form =
      form
      |> update_in([Access.key!(:params),"address_id"], &( String.to_integer(&1)))
      |> update_in([Access.key!(:params),"project_id"], &( String.to_integer(&1)))

    #Make LV aware of changes
    socket =
      socket
      |> assign(:form,form)

    {:noreply, socket}
  end 
```

Any advice or idea as to how this could be improved? And thanks again for the help!

**Comment by maxmarcon** [comment]
You're more than welcome.

> That helped thank you! But it an easy thing to overlook when working with database ids in forms. Which apparently get casted to strings by to_form or somewhere on the way...?

They're not always cast to string. However, a form built from an `Ecto.Changeset` will look for a field's value in the following places (and in this order):

1. The changes in the changeset
2. The params in the form
3. The original data structure in the changeset

See [here](https://github.com/phoenixframework/phoenix_ecto/blob/main/lib/phoenix_ecto/html.ex#L105)

1 and 3 are cast to the right data type, but 2 is always a string. 

If you `Ecto.Changeset.cast/4` some inputs, but they don't change the original data structure (i.e. you're passing id = 4 but your project has already id = 4), the "change" won't end up in the changeset's changes because it doesn't change the original data structure (it's not really a change). It will however end up in the form's params, and won't be cast to the correct data type.

I  think this is the behavior you're observing here.

You can overcome this by passing `force_changes: true` to cast. Then all your inputs should end up in the changest. Maybe give it a try?
