### ISSUE TITLE
Selections are immediately cleared/reset with Liveview 1.0

### ISSUE THREAD

**Issue by markolson-powerschool** [maxmarcon/live_select#72]
Upgrading our application to LV 1.0.0-rc.0, we're now seeing every LiveSelect with a value reset to its previous selection once the input has a blur event triggered.

There was a bug pre 1.0 where liveview wouldn't focus `readonly` inputs, meaning that blur events wouldn't fire afterwards, and we suspect that's what's triggering this behavior. Watching which `HANDLE EVENT` log messages come in, we do see that there is no `"blur"` event triggered with lv 0.20.14, but there is with 1.0.0-rc.0. 

Changing the dep to `{:phoenix_live_view, "==1.0.0-rc.0", override: true},` and updating the assets, you see this behavior on the sample app: 

https://github.com/maxmarcon/live_select/assets/160270281/6d11c7ab-d766-4b8e-aee2-0faacee8fcea

We can't think of a situation where blurring should reset the field, but wanted to see if there was some subtlety we were missing before making a PR that...
<strike>
- removed the call to `maybe_restore_selection` in `handle_event("blur", ...)`
- removed the call to `clear` in `handle_event("focus", ...)`, using `parent_event` consistently. 

Doing those two things gets the dropdown behaving as we'd expect, as best we can tell...
</strike>

Removing clear doesn't let you search again, of course..

https://github.com/maxmarcon/live_select/assets/160270281/47f6b72e-97d4-45ba-87bb-c39144354a87

**Comment by maxmarcon** [comment]
Hi and thanks for flagging this! I will have a look at this ASAP

**Comment by maxmarcon** [comment]
Hi @markolson-powerschool, I just pushed a fix for this specific problem on main, can you please check if it works for you?

> There was a bug pre 1.0 where liveview wouldn't focus readonly inputs

Confused because live view has been focusing my `readonly` (i.e. with an active selection) live_select input just fine so far.
However, when I run it against LV ` 1.0.0-rc.0.`, I no longer get a `focus` event when the user click on the field. Consequently, the field is not cleared and the user can't search:

https://github.com/maxmarcon/live_select/assets/11156096/2671e724-382f-4684-8f8b-feacf2458ea0

Pretty annoying. Why do you say that LV pre 1.0 wasn't focusing `readonly` inputs? If that was the case, live_select would have never worked.

**Comment by maxmarcon** [comment]
Even stranger: I do get the `focus` event after I submit the form


https://github.com/maxmarcon/live_select/assets/11156096/7337a7b7-237b-45d4-bbdc-37f44844656c


If you have any idea of what might be going on here, that'd would be very helpful :)

**Comment by maxmarcon** [comment]
FYI: I ran the showcase app against https://github.com/phoenixframework/phoenix_live_view/commit/c46af7dcf64403458cfebed537f0b4840894774b and the issues mentioned here didn't occur. So that's certainly _not_ the commit that introduced this bug

**Comment by maxmarcon** [comment]
Fixed with b31a9f8b93131789d60b85d49778e33623a2ee57
